# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-11 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Project')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
                ('token_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Token')),
            ],
        ),
    ]
