# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190312_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_question_id', to='api.Question'),
        ),
    ]
